### ISSUE TITLE
How to take snapshot backups on Minio/S3 from a running OpenEBS cluster?

### ISSUE THREAD

**Issue by ranjithwingrider** [openebs/openebs-docs#491]
Issue is raised by Deepak Sansaniwal in community channel

What is the strategy of taking snapshot backups on Minio/S3 from a running OpenEBS cluster so that we can externalize the app volume data to ensure redundant backup copies.

**Comment by deepak71** [comment]
As we've storage snapshot in OpenEBS for taking volume snapshots for backup/recovery and these snapshots data exists within k8s cluster only. Now, we want to externalize these snapshots data so that in worst case scenario if we need recovery of these PVCs then we can.

We've running Minio cluster on-prem and we want to leverage that instance for storing snapshots data. In out K8s cluster, we're running different type of workloads like DB, content management systems, logging system.

**Comment by ranjithwingrider** [comment]
@deepak71 There is one doc for Backup and Restore of OpenEBS volumes using Ark plugin. This doc is under review but you can follow the procedures listed there. 
https://docs.google.com/document/d/187NIogeudreKcRLC4v_11UnWbzb7YTUs2OCO0csh6LE/edit?usp=sharing

**Comment by ranjithwingrider** [comment]
@deepak71 We have added the procedure  in documentation. More can be read from here. https://docs.openebs.io/docs/next/backup.html
Your valuable feedback are always welcome. :-)
